# Movie Data Analysis: Data Preparation & Cleaning

This notebook documents the data preparation and cleaning steps applied to multiple
movie-related datasets. The objective is to standardize structure, correct data types,
handle missing values, and prepare the data for analysis.

# Phase 1: Data Preparation
Prepares the raw data by loading, inspecting, and standardizing dataset structure.
It focuses on column naming, missing value assessment, and removal of unusable fields, ensuring the data is ready for further processing.

## Stage 0: Setup & Imports

In this stage, we import the required Python libraries and configure the Jupyter
environment to support data analysis and visualization.

In [35]:
# Core data analysis libraries
import numpy as np
import pandas as pd
from plotnine import *  # generally not a good thing to do to import everything from a package. However it's ok for visualization purposes in an analysis.
import os
import scipy
import warnings
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"  # to make jupyter print all outputs, not just the last one
from IPython.core.display import HTML  # to pretty print pandas df and be able to copy them over (e.g. to ppt slides)

## Stage 1: Load the Data

Each dataset represents a different aspect of movie data:
- ExpertReviews: Professional critic reviews and scores
- UserReviews: User-generated reviews and feedback
- Meta: Movie metadata such as genre, studio, and ratings
- Sales: Box office and financial performance data

In [36]:
# Load datasets
# Each dataset represents a different aspect of movie data

expert_df = pd.read_csv("../Metacritic dataset/ExpertReviews.csv")

user_df = pd.read_csv(
    "../Metacritic dataset/UserReviews.csv",
    low_memory=False  # avoids dtype inference warnings
)

meta_df = pd.read_csv("../Metacritic dataset/metaClean43Brightspace.csv")

sales_df = pd.read_csv("../Metacritic dataset/sales.csv")

## Stage 2: Initial Data Inspection

We inspect the size and structure of each dataset by checking the number of rows,
columns, and column names.

In [37]:
print("There are {} rows and {} columns in the ExpertReviews.csv ".format(expert_df.shape[0], expert_df.shape[1]))
print("There are {} rows and {} columns in the UserReviews.csv ".format(user_df.shape[0], user_df.shape[1]))
print("There are {} rows and {} columns in the metaClean43Brightspace.csv ".format(meta_df.shape[0], meta_df.shape[1]))
print("There are {} rows and {} columns in the sales.csv ".format(sales_df.shape[0], sales_df.shape[1]))

There are 238973 rows and 5 columns in the ExpertReviews.csv
There are 319662 rows and 7 columns in the UserReviews.csv
There are 11364 rows and 13 columns in the metaClean43Brightspace.csv
There are 30612 rows and 16 columns in the sales.csv

## Stage 3: Column Name Standardization

Column names are standardized to improve readability, consistency,
and ease of merging across datasets.

### 3.1 Inspect the column names

In [38]:
print("Column names in ExpertReviews.csv:", list(expert_df.columns))
print("Columns names in UserReviews.csv ", list(user_df.columns))
print("Columns names in metaClean43Brightspace.csv ", list(meta_df.columns))
print("Columns names in sales.csv ", list(sales_df.columns))

Column names in ExpertReviews.csv: ['url', 'idvscore', 'reviewer', 'dateP', 'Rev']
Columns names in UserReviews.csv  ['url', 'idvscore', 'reviewer', 'dateP', 'Rev', 'thumbsUp', 'thumbsTot']
Columns names in metaClean43Brightspace.csv  ['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate']
Columns names in sales.csv  ['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'Unnamed: 8', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

### 3.2 Rename the column names

In [39]:
expert_df = expert_df.rename(columns={
    'idvscore': 'individual_score',
    'dateP': 'publish_date',
    'Rev': 'review_text'
})

user_df = user_df.rename(columns={
    'idvscore': 'individual_score',
    'dateP': 'publish_date',
    'Rev': 'review_text',
    'thumbsUp': 'thumbs_up',
    'thumbsTot': 'thumbs_total'
})

meta_df = meta_df.rename(columns={
    'RelDate': 'release_date',
    'metascore': 'meta_score',
    'userscore': 'user_score'
})

sales_df = sales_df.rename(columns={
    'international_box_office': 'intl_box_office',
    'domestic_box_office': 'dom_box_office',
    'worldwide_box_office': 'global_box_office',
    'avg run per theatre': 'avg_run_per_theatre',
    'Unnamed: 8': 'opening_weekend_revenue'
})

### 3.3 Verify column name changes

In [40]:
print("Column names in ExpertReviews.csv:", list(expert_df.columns))
print("Columns names in UserReviews.csv ", list(user_df.columns))
print("Columns names in metaClean43Brightspace.csv ", list(meta_df.columns))
print("Columns names in sales.csv ", list(sales_df.columns))

Column names in ExpertReviews.csv: ['url', 'individual_score', 'reviewer', 'publish_date', 'review_text']
Columns names in UserReviews.csv  ['url', 'individual_score', 'reviewer', 'publish_date', 'review_text', 'thumbs_up', 'thumbs_total']
Columns names in metaClean43Brightspace.csv  ['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'meta_score', 'user_score', 'release_date']
Columns names in sales.csv  ['year', 'release_date', 'title', 'genre', 'intl_box_office', 'dom_box_office', 'global_box_office', 'production_budget', 'opening_weekend_revenue', 'opening_weekend', 'theatre_count', 'avg_run_per_theatre', 'runtime', 'keywords', 'creative_type', 'url']

## Stage 4: Missing Value Analysis

We compute the number and percentage of missing values per column
to guide data cleaning decisions.

In [41]:
def missing_summary(df, name):
    summary = (
        df.isna()
        .sum()
        .to_frame(name='Missing Values')
        .assign(Percentage=lambda x: (x['Missing Values'] / len(df) * 100).round(2))
    )
    summary = summary[summary['Missing Values'] > 0]

    print(f"\n{name} — Missing Values Summary")
    print(summary if not summary.empty else "No missing values 🎉")

In [42]:
missing_summary(expert_df, "ExpertReviews")
missing_summary(user_df, "UserReviews")
missing_summary(meta_df, "Meta")
missing_summary(sales_df, "Sales")

ExpertReviews — Missing Values Summary
                  Missing Values  Percentage
individual_score               2         0.0
reviewer                       2         0.0
publish_date                   2         0.0
review_text                    2         0.0

UserReviews — Missing Values Summary
                  Missing Values  Percentage
individual_score            3404        1.06
reviewer                    3407        1.07
publish_date                3413        1.07
review_text                 3413        1.07
thumbs_up                   3580        1.12
thumbs_total                3576        1.12

Meta — Missing Values Summary
            Missing Values  Percentage
studio                 350        3.08
rating                1067        9.39
runtime                255        2.24
cast                  3702       32.58
director                14        0.12
genre                   20        0.18
summary               5897       51.89
awards                6977       61.40
user_score            2105       18.52

Sales — Missing Values Summary
                         Missing Values  Percentage
title                                 8        0.03
genre                              1704        5.57
intl_box_office                    9037       29.52
dom_box_office                    18728       61.18
global_box_office                  9037       29.52
production_budget                 26132       85.37
opening_weekend_revenue           30612      100.00
opening_weekend                   19683       64.30
theatre_count                     19649       64.19
avg_run_per_theatre               19660       64.22
runtime                            6053       19.77
keywords                          18095       59.11
creative_type                      3945       12.89

## Stage 5: Removal of Unusable Columns

Columns that contain little or no meaningful information are removed
to simplify the datasets and reduce noise.

In [43]:
# Drop fully empty columns
sales_df = sales_df.drop(columns=[
    'opening_weekend_revenue'
])

print("Columns names in sales.csv ", list(sales_df.columns))

Columns names in sales.csv  ['year', 'release_date', 'title', 'genre', 'intl_box_office', 'dom_box_office', 'global_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg_run_per_theatre', 'runtime', 'keywords', 'creative_type', 'url']

# Phase 2: Data Type Correction and Semantic Cleaning

Phase 2 focuses on correcting and validating data types for each dataset individually.
The goal is to ensure semantic correctness and consistency before defining relationships
or performing any dataset integration.

## Stage 0: ExpertReviews

This stage focuses on inspecting and correcting data types in the ExpertReviews dataset.

During inspection, additional issues related to missing values and text formatting
were observed. Since these issues are limited to individual columns and do not
affect table relationships, basic normalization is performed as part of Phase 2.
More advanced text processing will be addressed in a later phase.

### 0.1 Data Type Inspection

We inspect both the data types and a sample of the data to understand
the structure and content of each column before applying any corrections.

In [44]:
# Inspect data types
print(expert_df.dtypes)

# View sample rows
expert_df.head(50)

url                  object
individual_score    float64
reviewer             object
publish_date         object
review_text          object
dtype: object

,url,individual_score,reviewer,publish_date,review_text
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,..."
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of..."
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl..."
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'"
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act..."
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i..."
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize..."
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ..."
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti..."
20,https://www.metacritic.com/movie/bronson,30.0,'J. Hoberman',None,"'Bronson is essentially a faux-operatic, musi..."
21,https://www.metacritic.com/movie/bronson,25.0,'Walter Addiego',None,'It s an assaultive work about an assaultive ...
22,https://www.metacritic.com/movie/disgrace,100.0,'Roger Ebert',None,'This is such a rare movie. Its characters ar...
23,https://www.metacritic.com/movie/disgrace,90.0,'Stephen Holden',None,'Mr. Malkovich is one of the few actors capab...
24,https://www.metacritic.com/movie/disgrace,83.0,'Peter Rainer',None,"'As fiercely unsentimental as Disgrace is, it..."
25,https://www.metacritic.com/movie/disgrace,80.0,None,None,"'The austere economy of Coetzee s writing, cr..."
26,https://www.metacritic.com/movie/disgrace,80.0,'Bob Mondello',None,'John Malkovich has played some odd ducks in ...
27,https://www.metacritic.com/movie/disgrace,80.0,None,None,'Surprisingly successful adaptation of J. M. ...
28,https://www.metacritic.com/movie/disgrace,75.0,'V.A. Musetto',None,'I cannot tell a lie. I derive great satisfac...
29,https://www.metacritic.com/movie/disgrace,75.0,'Lisa Schwarzbaum',None,'Newcomer Jessica Haines is transparent and h...
30,https://www.metacritic.com/movie/disgrace,75.0,'Ty Burr',None,"'It s a harsh experience, at times engrossing..."
31,https://www.metacritic.com/movie/disgrace,70.0,'Eddie Cockrell',None,'Anchored by another marvelously quirky yet d...
32,https://www.metacritic.com/movie/disgrace,70.0,'J.R. Jones',None,'The movie eventually begins to wilt under th...
33,https://www.metacritic.com/movie/disgrace,70.0,'Joe Morgenstern',None,"'Nothing is simple in this film, which ramifi..."
34,https://www.metacritic.com/movie/disgrace,70.0,None,None,"'Absorbing but often bloodless and, frankly, ..."
35,https://www.metacritic.com/movie/disgrace,67.0,'Keith Phipps',None,'After a compelling opening act and some shoc...
36,https://www.metacritic.com/movie/disgrace,60.0,None,None,'The story often appears a little unreal.'
37,https://www.metacritic.com/movie/disgrace,60.0,'Philip Kennicott',None,'Is it a great movie? John Malkovich s portra...
38,https://www.metacritic.com/movie/disgrace,40.0,None,None,'A frustrating film full of overplayed men-as...
39,https://www.metacritic.com/movie/disgrace,40.0,'Joe Neumaier',None,"'The film, unfortunately, hasn t the depth Ma..."
40,https://www.metacritic.com/movie/a-screaming-man,90.0,'Manohla Dargis',"'Apr 14, 2011'","'It s a modest film, if only in scale and app..."
41,https://www.metacritic.com/movie/a-screaming-man,83.0,'Eric Kohn',"'Apr 12, 2011'","'At its core, A Screaming Man emphasizes the ..."
42,https://www.metacritic.com/movie/a-screaming-man,80.0,'Robert Koehler',"'May 26, 2013'",'Haroun s tender but unsentimental regard for...
43,https://www.metacritic.com/movie/a-screaming-man,80.0,'David Fear',"'Apr 12, 2011'",'A collective sense of psychological turmoil ...
44,https://www.metacritic.com/movie/a-screaming-man,70.0,None,"'Apr 12, 2011'",'Haroun is uninterested in big war scenes and...
45,https://www.metacritic.com/movie/a-screaming-man,60.0,None,"'Apr 16, 2011'",'The first half-hour is as evocative as (and ...
46,https://www.metacritic.com/movie/a-screaming-man,60.0,'Joe Neumaier',"'Apr 15, 2011'",'Haroun is achingly conscious of day-to-day d...
47,https://www.metacritic.com/movie/a-screaming-man,50.0,'Nick Pinkerton',"'Apr 12, 2011'",'The characterizations never comfortably acco...
48,https://www.metacritic.com/movie/lovers-of-hate,91.0,'Eric Kohn',"'Feb 10, 2011'",'Never indulging in outright scare tactics or...
49,https://www.metacritic.com/movie/lovers-of-hate,90.0,'Jeannette Catsoulis',"'Feb 10, 2011'","'Smartly written and flawlessly acted, Lovers..."

**Inspection summary:**

- `url` (object): Correct, used as an identifier
- `individual_score` (float64): Correct numeric type
- `reviewer` (object): Correct type, but contains missing values and inconsistent quoting
- `publish_date` (object): Incorrect type, should be datetime
- `review_text` (object): Correct type, but contains formatting artifacts and missing values

### 0.2 Data Type and Basic Semantic Corrections

Based on the inspection, we apply the following corrections:
- Convert `publish_date` to datetime
- Normalize missing values in text fields
- Remove obvious quoting artifacts from text columns

These corrections are limited to column-level normalization and do not
alter the semantic meaning of the data.
python
Copy code

In [45]:
# Convert publish_date to datetime
expert_df['publish_date'] = pd.to_datetime(
    expert_df['publish_date'], errors='coerce'
)

# Normalize reviewer column
expert_df['reviewer'] = (
    expert_df['reviewer']
    .replace('None', pd.NA)
    .str.strip(' "\'')
)

# Normalize review_text column
expert_df['review_text'] = (
    expert_df['review_text']
    .astype(str)
    .str.strip(' "\'')
    .replace('None', pd.NA)
)

C:\Users\mhama\AppData\Local\Temp\ipykernel_29428\1668252629.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

### 0.3 Post-correction Verification

We re-inspect a sample of the data to verify that the corrections
have been applied as intended.

In [46]:
# View sample rows
expert_df.head(50)

,url,individual_score,reviewer,publish_date,review_text
0,https://www.metacritic.com/movie/bronson,100.0,Andrew O'Hehir,NaT,Bronson owes a little or a lot to Kubrick s Cl...
1,https://www.metacritic.com/movie/bronson,90.0,A.O. Scott,NaT,Bronson invites you to admire its protagonist ...
2,https://www.metacritic.com/movie/bronson,90.0,None,NaT,Whether it s Peterson/Bronson s more theatrica...
3,https://www.metacritic.com/movie/bronson,83.0,Noel Murray,NaT,There are two Bronsons on display here: the im...
4,https://www.metacritic.com/movie/bronson,80.0,Joshua Rothkopf,NaT,Refn has somehow found his way to an authentic...
5,https://www.metacritic.com/movie/bronson,80.0,None,NaT,"He s neither victim nor hero, but a man who, i..."
6,https://www.metacritic.com/movie/bronson,80.0,Bill Goodykoontz,NaT,"This is unhinged genius, an amazing piece of a..."
7,https://www.metacritic.com/movie/bronson,78.0,Kimberley Jones,NaT,Refn s artful and energetic film never goes fu...
8,https://www.metacritic.com/movie/bronson,75.0,Peter Travers,NaT,This movie and Hardy s electrifying performanc...
9,https://www.metacritic.com/movie/bronson,75.0,V.A. Musetto,NaT,Tom Hardy gives an amazing performance as Pete...
10,https://www.metacritic.com/movie/bronson,75.0,David Hiltbrand,NaT,"The tone is surreal, at once visceral and clin..."
11,https://www.metacritic.com/movie/bronson,75.0,Roger Ebert,NaT,"It is 92 minutes of rage, acted by Tom Hardy."
12,https://www.metacritic.com/movie/bronson,75.0,Michael Phillips,NaT,"Hardy is remarkable, however. This is an actor..."
13,https://www.metacritic.com/movie/bronson,75.0,Ty Burr,NaT,Bronson isn t a story in the traditional sense...
14,https://www.metacritic.com/movie/bronson,75.0,Shawn Levy,NaT,"It s played with real zest and energy, and if ..."
15,https://www.metacritic.com/movie/bronson,70.0,None,NaT,"With an intelligent, provocative and stylized ..."
16,https://www.metacritic.com/movie/bronson,63.0,James Berardinelli,NaT,It s lively and vivid but ends up leaving the ...
17,https://www.metacritic.com/movie/bronson,60.0,None,NaT,"Too smart/arty for the slasher set, and too vi..."
18,https://www.metacritic.com/movie/bronson,50.0,Rick Groen,NaT,Bronson is one of those based on a true story ...
19,https://www.metacritic.com/movie/bronson,30.0,None,NaT,"Despite the artistic flourishes, this is still..."
20,https://www.metacritic.com/movie/bronson,30.0,J. Hoberman,NaT,"Bronson is essentially a faux-operatic, music ..."
21,https://www.metacritic.com/movie/bronson,25.0,Walter Addiego,NaT,It s an assaultive work about an assaultive fe...
22,https://www.metacritic.com/movie/disgrace,100.0,Roger Ebert,NaT,This is such a rare movie. Its characters are ...
23,https://www.metacritic.com/movie/disgrace,90.0,Stephen Holden,NaT,Mr. Malkovich is one of the few actors capable...
24,https://www.metacritic.com/movie/disgrace,83.0,Peter Rainer,NaT,"As fiercely unsentimental as Disgrace is, it o..."
25,https://www.metacritic.com/movie/disgrace,80.0,None,NaT,"The austere economy of Coetzee s writing, cris..."
26,https://www.metacritic.com/movie/disgrace,80.0,Bob Mondello,NaT,John Malkovich has played some odd ducks in hi...
27,https://www.metacritic.com/movie/disgrace,80.0,None,NaT,Surprisingly successful adaptation of J. M. Co...
28,https://www.metacritic.com/movie/disgrace,75.0,V.A. Musetto,NaT,I cannot tell a lie. I derive great satisfacti...
29,https://www.metacritic.com/movie/disgrace,75.0,Lisa Schwarzbaum,NaT,Newcomer Jessica Haines is transparent and hea...
30,https://www.metacritic.com/movie/disgrace,75.0,Ty Burr,NaT,"It s a harsh experience, at times engrossing, ..."
31,https://www.metacritic.com/movie/disgrace,70.0,Eddie Cockrell,NaT,Anchored by another marvelously quirky yet dea...
32,https://www.metacritic.com/movie/disgrace,70.0,J.R. Jones,NaT,The movie eventually begins to wilt under the ...
33,https://www.metacritic.com/movie/disgrace,70.0,Joe Morgenstern,NaT,"Nothing is simple in this film, which ramifies..."
34,https://www.metacritic.com/movie/disgrace,70.0,None,NaT,"Absorbing but often bloodless and, frankly, de..."
35,https://www.metacritic.com/movie/disgrace,67.0,Keith Phipps,NaT,After a compelling opening act and some shocki...
36,https://www.metacritic.com/movie/disgrace,60.0,None,NaT,The story often appears a little unreal.
37,https://www.metacritic.com/movie/disgrace,60.0,Philip Kennicott,NaT,Is it a great movie? John Malkovich s portraya...
38,https://www.metacritic.com/movie/disgrace,40.0,None,NaT,A frustrating film full of overplayed men-as-d...
39,https://www.metacritic.com/movie/disgrace,40.0,Joe Neumaier,NaT,"The film, unfortunately, hasn t the depth Malk..."
40,https://www.metacritic.com/movie/a-screaming-man,90.0,Manohla Dargis,2011-04-14,"It s a modest film, if only in scale and appar..."
41,https://www.metacritic.com/movie/a-screaming-man,83.0,Eric Kohn,2011-04-12,"At its core, A Screaming Man emphasizes the st..."
42,https://www.metacritic.com/movie/a-screaming-man,80.0,Robert Koehler,2013-05-26,Haroun s tender but unsentimental regard for h...
43,https://www.metacritic.com/movie/a-screaming-man,80.0,David Fear,2011-04-12,A collective sense of psychological turmoil se...
44,https://www.metacritic.com/movie/a-screaming-man,70.0,None,2011-04-12,Haroun is uninterested in big war scenes and i...
45,https://www.metacritic.com/movie/a-screaming-man,60.0,None,2011-04-16,The first half-hour is as evocative as (and mo...
46,https://www.metacritic.com/movie/a-screaming-man,60.0,Joe Neumaier,2011-04-15,Haroun is achingly conscious of day-to-day dec...
47,https://www.metacritic.com/movie/a-screaming-man,50.0,Nick Pinkerton,2011-04-12,The characterizations never comfortably accomm...
48,https://www.metacritic.com/movie/lovers-of-hate,91.0,Eric Kohn,2011-02-10,Never indulging in outright scare tactics or l...
49,https://www.metacritic.com/movie/lovers-of-hate,90.0,Jeannette Catsoulis,2011-02-10,"Smartly written and flawlessly acted, Lovers o..."

## Stage 1: UserReviews

This stage focuses on inspecting and correcting data types and basic semantic issues
in the UserReviews dataset. Compared to ExpertReviews, this table contains additional
numeric counts and more frequent missing values.

### 1.1 Data Type Inspection

We inspect both the data types and a sample of the data to understand
the structure, content, and quality of each column before applying corrections.

In [47]:
# Inspect data types
print(user_df.dtypes)

# Inspect sample rows
user_df.head(50)

url                 object
individual_score    object
reviewer            object
publish_date        object
review_text         object
thumbs_up           object
thumbs_total        object
dtype: object

,url,individual_score,reviewer,publish_date,review_text,thumbs_up,thumbs_total
0,https://www.metacritic.com/movie/bronson,8,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,2,2
1,https://www.metacritic.com/movie/bronson,9,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,0,1
2,https://www.metacritic.com/movie/bronson,10,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,1,1
3,https://www.metacritic.com/movie/bronson,6,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,0,1
4,https://www.metacritic.com/movie/bronson,8,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,0,0
5,https://www.metacritic.com/movie/bronson,8,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni...",0,0
6,https://www.metacritic.com/movie/bronson,8,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ...",0,0
7,https://www.metacritic.com/movie/bronson,7,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...,0,0
8,https://www.metacritic.com/movie/bronson,4,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...,0,0
9,https://www.metacritic.com/movie/bronson,10,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...,0,0
10,https://www.metacritic.com/movie/bronson,4,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl...",0,0
11,https://www.metacritic.com/movie/bronson,8,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...,0,0
12,https://www.metacritic.com/movie/bronson,5,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi...",0,0
13,https://www.metacritic.com/movie/bronson,3,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r...",0,0
14,https://www.metacritic.com/movie/bronson,5,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...,0,0
15,https://www.metacritic.com/movie/bronson,7,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil...",0,0
16,https://www.metacritic.com/movie/bronson,8,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d...",0,0
17,https://www.metacritic.com/movie/bronson,9,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...,0,0
18,https://www.metacritic.com/movie/bronson,9,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...,0,0
19,https://www.metacritic.com/movie/bronson,5,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,...",0,0
20,https://www.metacritic.com/movie/bronson,8,'nbock',"'Aug 26, 2015'",'While Bronson does take several creative lib...,0,0
21,https://www.metacritic.com/movie/bronson,3,'Broyax',"'Jan 27, 2017'","'J avais vu la bande-annonce, tr s dr le, et ...",0,0
22,https://www.metacritic.com/movie/bronson,7,'AndrewBurge',"'Jan 31, 2019'",'This film is so British that I want to send ...,0,0
23,https://www.metacritic.com/movie/bronson,6,'ahmedaiman1999',"'Mar 20, 2019'",'This is definitely a one-of-a-kind character...,0,0
24,https://www.metacritic.com/movie/bronson,10,'Mclovin69',"'Apr 5, 2021'","'The movie was hilarious, Michael peterson wa...",0,0
25,https://www.metacritic.com/movie/bronson,9,'TUMBLERok',"'Jun 22, 2020'","' , , . . ! . , , . . ! . , , Bronson . . . 9...",0,0
26,https://www.metacritic.com/movie/bronson,9,'Honestyopinons',"'Jun 27, 2020'",'one of the best movies about insanity withou...,0,0
27,https://www.metacritic.com/movie/disgrace,0,'Nazgulero',"'Feb 27, 2011'",'After watching this horrible movie for thirt...,0,3
28,https://www.metacritic.com/movie/disgrace,10,'wwh',"'Aug 2, 2011'",'Re: seems quite disgusted by him right from ...,0,0
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN,NaN,NaN
30,https://www.metacritic.com/movie/lovers-of-hate,NaN,NaN,NaN,NaN,NaN,NaN
31,https://www.metacritic.com/movie/phil-ochs-the...,9,'Biff_Loman',"'Apr 17, 2011'","'The film captures the grimness of that era, ...",0,0
32,https://www.metacritic.com/movie/phil-ochs-the...,8,'Brucenelson',"'Mar 4, 2011'","'Did a good job of his protest years, but did...",0,0
33,https://www.metacritic.com/movie/phil-ochs-the...,10,'Metaman101',"'Dec 7, 2011'",'Terrific film about Ochs and the sixties you...,0,0
34,https://www.metacritic.com/movie/viva-riva!,NaN,NaN,NaN,NaN,NaN,NaN
35,https://www.metacritic.com/movie/puss-in-boots,8,'simpletaste',"'Feb 3, 2012'",'Puss in Boots is a very good Action Adventur...,3,3
36,https://www.metacritic.com/movie/puss-in-boots,9,'JPK',"'Mar 3, 2018'",'Very Well DoneThis Is The Story That Puss Ne...,1,1
37,https://www.metacritic.com/movie/puss-in-boots,7,'grandpajoe6191',"'Feb 13, 2012'","'It s not one of the year s best, but it cert...",11,12
38,https://www.metacritic.com/movie/puss-in-boots,7,'Audiowombat',"'Oct 29, 2011'",'Fully entertaining for both the kids and adu...,3,6
39,https://www.metacritic.com/movie/puss-in-boots,8,'Sir_Brandon',"'Nov 10, 2011'",'Ever since Puss in Boots (Antonio Banderas) ...,1,2
40,https://www.metacritic.com/movie/puss-in-boots,2,'Friskytiger81',"'Mar 15, 2012'",'Unwatchable. This is what spin-offs are. Dre...,1,2
41,https://www.metacritic.com/movie/puss-in-boots,8,'movieman24fps',"'Oct 31, 2011'","'Sharp, witty fun, this Shrek spin-off is loa...",1,2
42,https://www.metacritic.com/movie/puss-in-boots,10,'zaxmazr',"'Nov 14, 2011'","'Haha, what s there to say that s bad about t...",1,2
43,https://www.metacritic.com/movie/puss-in-boots,8,'DarkCritic',"'Oct 30, 2011'",'Puss in Boots is very good spin-off and I en...,2,5
44,https://www.metacritic.com/movie/puss-in-boots,10,'RogerSmith97',"'Nov 4, 2011'",'All I Can Is THE BEST MOVIE OF 2011 & CD ANI...,3,9
45,https://www.metacritic.com/movie/puss-in-boots,2,'Princess_Peach',"'Dec 11, 2011'",'Mediocre cartoon. Too much adult humor. Too ...,1,6
46,https://www.metacritic.com/movie/puss-in-boots,9,'adelezaaba',"'Nov 27, 2011'",'Fantastic graphic and action scenes. An ulti...,0,1
47,https://www.metacritic.com/movie/puss-in-boots,7,'scrieciu',"'Oct 31, 2011'","' Puss in Boots is a good, fun, enjoyable mov...",0,1
48,https://www.metacritic.com/movie/puss-in-boots,10,'PurpleUrp',"'Nov 15, 2011'",'PIB astounded me not only with his voice but...,0,1
49,https://www.metacritic.com/movie/puss-in-boots,6,'moviemonger',"'Nov 13, 2011'",'Your first question should be What do I expe...,0,1

**Inspection summary:**

- `url` (object): Correct, used as an identifier
- `individual_score` (object): Should be numeric
- `reviewer` (object): Correct type, contains missing values
- `publish_date` (object): Should be datetime
- `review_text` (object): Correct type, contains formatting artifacts and duplication
- `thumbs_up` (object): Should be integer count
- `thumbs_total` (object): Should be integer count

### 1.2 Data Type and Basic Semantic Corrections

Based on the inspection, we apply the following corrections:
- Convert numeric columns to appropriate numeric types
- Convert publish_date to datetime
- Normalize missing values in text columns
- Preserve text meaning while removing obvious artifacts

In [48]:
# Drop rows that contain no usable review information
user_df = user_df.dropna(
    subset=['individual_score', 'review_text', 'publish_date'],
    how='all'
)

# Convert individual_score to numeric
user_df['individual_score'] = pd.to_numeric(
    user_df['individual_score'], errors='coerce'
)

# Clean and convert publish_date
user_df['publish_date'] = (
    user_df['publish_date']
    .astype(str)
    .str.strip(' "\'')
)

user_df['publish_date'] = pd.to_datetime(
    user_df['publish_date'], errors='coerce'
)

# Convert thumbs counts to nullable integers
user_df['thumbs_up'] = pd.to_numeric(
    user_df['thumbs_up'], errors='coerce'
).astype('Int64')

user_df['thumbs_total'] = pd.to_numeric(
    user_df['thumbs_total'], errors='coerce'
).astype('Int64')

# Normalize reviewer column
user_df['reviewer'] = (
    user_df['reviewer']
    .replace('None', pd.NA)
    .str.strip(' "\'')
)

# Normalize review_text column
user_df['review_text'] = (
    user_df['review_text']
    .astype(str)
    .str.strip(' "\'')
    .replace('None', pd.NA)
)

### 1.3 Post-correction Verification

We re-inspect a sample of the data to confirm that the corrections
have been applied correctly and that no unintended changes were introduced.

In [49]:

# Verify sample rows
user_df.head(50)

,url,individual_score,reviewer,publish_date,review_text,thumbs_up,thumbs_total
0,https://www.metacritic.com/movie/bronson,8.0,Longbottom94,2013-04-25,Many have dismissed this film for not explorin...,2,2
1,https://www.metacritic.com/movie/bronson,9.0,MartinB,2009-10-13,Anyone who doesn t like this movie simply just...,0,1
2,https://www.metacritic.com/movie/bronson,10.0,Jaakko,2012-07-19,Not sure what to think at this film at first. ...,1,1
3,https://www.metacritic.com/movie/bronson,6.0,CapoR,2009-10-13,Nicely portrayed but it lacks the elements to ...,0,1
4,https://www.metacritic.com/movie/bronson,8.0,OrwellB.,2009-10-10,Bronson is more than entertainment. It is art ...,0,0
5,https://www.metacritic.com/movie/bronson,8.0,RONGIU,2011-06-10,"Sorry, machine translation. The stage, by Nico...",0,0
6,https://www.metacritic.com/movie/bronson,8.0,Tokyochuchu,2013-11-30,"Bronson is a great, extremely strange movie fr...",0,0
7,https://www.metacritic.com/movie/bronson,7.0,Fenrir81,2011-04-22,Despite being flawed by a weak narrative struc...,0,0
8,https://www.metacritic.com/movie/bronson,4.0,cabrita,2012-08-10,If valhalla rising was a weak version of aggui...,0,0
9,https://www.metacritic.com/movie/bronson,10.0,farknash,2011-08-19,http://mikesharkey.blogspot.com/2009/04/igizmo...,0,0
10,https://www.metacritic.com/movie/bronson,4.0,Spangle,2015-03-06,"Extremely claustrophobic, Bronson is possibly ...",0,0
11,https://www.metacritic.com/movie/bronson,8.0,Nesbitt10,2013-07-04,One thing is for certain: Bronson invites you ...,0,0
12,https://www.metacritic.com/movie/bronson,5.0,TrilobiteG,2016-01-06,"Got to say, I m rather disappointed. To begin ...",0,0
13,https://www.metacritic.com/movie/bronson,3.0,Luxocell,2015-01-16,"Call me simple minded if you desire, but I rea...",0,0
14,https://www.metacritic.com/movie/bronson,5.0,TomBeltran,2013-05-27,Posted on 5/20/13 10:15 AM\rTom hardy gives a ...,0,0
15,https://www.metacritic.com/movie/bronson,7.0,BrettT,2014-06-08,"Well acted and gritty, Bronson is a good film....",0,0
16,https://www.metacritic.com/movie/bronson,8.0,Voltronix,2014-08-14,"Tom Hardy nails it in this role, partially due...",0,0
17,https://www.metacritic.com/movie/bronson,9.0,LatinCritic13,2019-04-07,Bronson is defined as a film that s notorious ...,0,0
18,https://www.metacritic.com/movie/bronson,9.0,MattBrady99,2015-09-09,Bronson follows the life of notorious prisoner...,0,0
19,https://www.metacritic.com/movie/bronson,5.0,Ralfbergs,2016-06-25,"I really liked TOm Hardy s performance here, b...",0,0
20,https://www.metacritic.com/movie/bronson,8.0,nbock,2015-08-26,While Bronson does take several creative liber...,0,0
21,https://www.metacritic.com/movie/bronson,3.0,Broyax,2017-01-27,"J avais vu la bande-annonce, tr s dr le, et j ...",0,0
22,https://www.metacritic.com/movie/bronson,7.0,AndrewBurge,2019-01-31,This film is so British that I want to send it...,0,0
23,https://www.metacritic.com/movie/bronson,6.0,ahmedaiman1999,2019-03-20,This is definitely a one-of-a-kind character s...,0,0
24,https://www.metacritic.com/movie/bronson,10.0,Mclovin69,2021-04-05,"The movie was hilarious, Michael peterson was ...",0,0
25,https://www.metacritic.com/movie/bronson,9.0,TUMBLERok,2020-06-22,", , . . ! . , , . . ! . , , Bronson . . . 9/10.",0,0
26,https://www.metacritic.com/movie/bronson,9.0,Honestyopinons,2020-06-27,one of the best movies about insanity without ...,0,0
27,https://www.metacritic.com/movie/disgrace,0.0,Nazgulero,2011-02-27,After watching this horrible movie for thirty ...,0,3
28,https://www.metacritic.com/movie/disgrace,10.0,wwh,2011-08-02,Re: seems quite disgusted by him right from th...,0,0
31,https://www.metacritic.com/movie/phil-ochs-the...,9.0,Biff_Loman,2011-04-17,"The film captures the grimness of that era, th...",0,0
32,https://www.metacritic.com/movie/phil-ochs-the...,8.0,Brucenelson,2011-03-04,"Did a good job of his protest years, but didn ...",0,0
33,https://www.metacritic.com/movie/phil-ochs-the...,10.0,Metaman101,2011-12-07,Terrific film about Ochs and the sixties youth...,0,0
35,https://www.metacritic.com/movie/puss-in-boots,8.0,simpletaste,2012-02-03,Puss in Boots is a very good Action Adventure ...,3,3
36,https://www.metacritic.com/movie/puss-in-boots,9.0,JPK,2018-03-03,Very Well DoneThis Is The Story That Puss Need...,1,1
37,https://www.metacritic.com/movie/puss-in-boots,7.0,grandpajoe6191,2012-02-13,"It s not one of the year s best, but it certai...",11,12
38,https://www.metacritic.com/movie/puss-in-boots,7.0,Audiowombat,2011-10-29,Fully entertaining for both the kids and adult...,3,6
39,https://www.metacritic.com/movie/puss-in-boots,8.0,Sir_Brandon,2011-11-10,Ever since Puss in Boots (Antonio Banderas) sh...,1,2
40,https://www.metacritic.com/movie/puss-in-boots,2.0,Friskytiger81,2012-03-15,Unwatchable. This is what spin-offs are. Dream...,1,2
41,https://www.metacritic.com/movie/puss-in-boots,8.0,movieman24fps,2011-10-31,"Sharp, witty fun, this Shrek spin-off is loads...",1,2
42,https://www.metacritic.com/movie/puss-in-boots,10.0,zaxmazr,2011-11-14,"Haha, what s there to say that s bad about thi...",1,2
43,https://www.metacritic.com/movie/puss-in-boots,8.0,DarkCritic,2011-10-30,Puss in Boots is very good spin-off and I enjo...,2,5
44,https://www.metacritic.com/movie/puss-in-boots,10.0,RogerSmith97,2011-11-04,All I Can Is THE BEST MOVIE OF 2011 & CD ANIMA...,3,9
45,https://www.metacritic.com/movie/puss-in-boots,2.0,Princess_Peach,2011-12-11,Mediocre cartoon. Too much adult humor. Too ma...,1,6
46,https://www.metacritic.com/movie/puss-in-boots,9.0,adelezaaba,2011-11-27,Fantastic graphic and action scenes. An ultima...,0,1
47,https://www.metacritic.com/movie/puss-in-boots,7.0,scrieciu,2011-10-31,"Puss in Boots is a good, fun, enjoyable movie ...",0,1
48,https://www.metacritic.com/movie/puss-in-boots,10.0,PurpleUrp,2011-11-15,PIB astounded me not only with his voice but w...,0,1
49,https://www.metacritic.com/movie/puss-in-boots,6.0,moviemonger,2011-11-13,Your first question should be What do I expect...,0,1
50,https://www.metacritic.com/movie/puss-in-boots,8.0,yarr,2011-11-14,"A fun, light-hearted romp throug the origins a...",0,1
51,https://www.metacritic.com/movie/puss-in-boots,8.0,Knicksfan7,2011-11-01,This movie was just plain fun. Not as good as ...,0,1
52,https://www.metacritic.com/movie/puss-in-boots,4.0,acarmatt,2011-10-31,"I enjoyed the first 20 minutes or so, but once...",0,2

## Stage 2: Meta

This stage focuses on inspecting and correcting data types and basic semantic issues
in the Meta dataset. This table contains descriptive movie metadata, including
categorical variables and numeric scores, which will later be used for grouping
and analysis.

### 2.1 Data Type Inspection

We inspect both the data types and a sample of the data to understand
the structure, content, and quality of each column before applying corrections.

In [50]:
# Inspect data types
print(meta_df.dtypes)

# Inspect sample rows
meta_df.head(50)

url              object
title            object
studio           object
rating           object
runtime         float64
cast             object
director         object
genre            object
summary          object
awards           object
meta_score        int64
user_score      float64
release_date     object
dtype: object

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,meta_score,user_score,release_date
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,01/06/2011
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,11/03/2016
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,01/12/2006
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,14/09/2012
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,28/06/2013
5,https://www.metacritic.com/movie/100-streets,100 Streets,Samuel Goldwyn Films,NaN,93.0,NaN,Jim O'Hanlon,Drama,NaN,NaN,44,6.1,13/01/2017
6,https://www.metacritic.com/movie/1000-times-go...,"1,000 Times Good Night",Film Movement,| Not Rated,117.0,NaN,Erik Poppe,Drama,NaN,NaN,57,6.8,24/10/2014
7,https://www.metacritic.com/movie/10000-bc,"10,000 BC",Warner Bros. Pictures,| PG-13,109.0,"Camilla Belle,Marco Khan,Steven Strait",Roland Emmerich,"Adventure,Drama,Fantasy",NaN,"#23MostDiscussedMovieof2008 , #27MostSharedMov...",34,4.6,07/03/2008
8,https://www.metacritic.com/movie/10000-km,"10,000 km",Broad Green Pictures,| R,99.0,NaN,Carlos Marques-Marcet,"Drama,Comedy,Romance","Two people in love, two apartments - one in Ba...",NaN,75,7.4,10/07/2015
9,https://www.metacritic.com/movie/1001-grams,1001 Grams,Kino Lorber,| Not Rated,93.0,NaN,Bent Hamer,Drama,When Norwegian scientist Marie attends a semin...,NaN,65,NaN,08/05/2015
10,https://www.metacritic.com/movie/101-reykjavik,ReykjavÃ­k,Menemsha Entertainment,| Not Rated,88.0,"Hilmir SnÃ¦r GuÃ°nason,Victoria Abril",Baltasar KormÃ¡kur,"Comedy,Romance",A young man's sexual impulses go haywire when ...,NaN,68,5.4,25/07/2001
11,https://www.metacritic.com/movie/102-dalmatians,102 Dalmatians,Buena Vista Pictures,| G,100.0,"GÃ©rard Depardieu,Glenn Close",Kevin Lima,"Comedy,Family",Just when it seemed safe to come out of the ke...,#73MostDiscussedMovieof2000,35,5.1,22/11/2000
12,https://www.metacritic.com/movie/10th-wolf,10th & Wolf,THINKFilm,| R,107.0,"Brad Renfro,Giovanni Ribisi,James Marsden",Robert Moresco,"Drama,Mystery,Thriller,Crime",A Philadelphia mob war is the backdrop of 10th...,NaN,36,6.7,18/08/2006
13,https://www.metacritic.com/movie/11-flowers,11 Flowers,First Run Features,| Not Rated,110.0,NaN,Xiaoshuai Wang,Drama,When 11-year-old Wang is selected to lead his ...,NaN,71,NaN,22/02/2013
14,https://www.metacritic.com/movie/11-minutes,11 Minutes,IFC Films,| Not Rated,81.0,NaN,Jerzy Skolimowski,"Drama,Thriller","In a city square in Warsaw, a sleazy film dire...",NaN,51,7.5,08/04/2016
15,https://www.metacritic.com/movie/11816,11/8/16,The Orchard,| TV-MA,104.0,Abby Linne,Alison Klayman,Documentary,"On the morning of Election Day 2016, Americans...",NaN,62,NaN,03/11/2017
16,https://www.metacritic.com/movie/12,12,Sony Pictures Classics,| PG-13,159.0,"Apti Magamaev,Sergei Makovetsky,Sergey Garmash",Nikita Mikhalkov,"Drama,Thriller,Crime,War",NaN,"#97BestMovieof2009 , #18MostSharedMovieof2009",72,7.4,04/03/2009
17,https://www.metacritic.com/movie/12-12-12,12-12-12,"Weinstein Company, The",| R,105.0,NaN,Amir Bar-Lev,Documentary,A behind-the-scenes look at the televised bene...,NaN,54,NaN,15/11/2013
18,https://www.metacritic.com/movie/12-hour-shift,12 Hour Shift,Magnet Releasing,| Not Rated,87.0,"Angela Bettis,Brooke Seguin,Chloe Farnworth,Da...",Brea Grant,"Thriller,Horror,Comedy",NaN,NaN,63,5.8,02/10/2020
19,https://www.metacritic.com/movie/12-mighty-orp...,12 Mighty Orphans,Sony Pictures Classics,| PG-13,118.0,"Carlson Young,Jacob Lofland,Jake Austin Walker...",Ty Roberts,"History,Sport",NaN,NaN,44,6.6,11/06/2021
20,https://www.metacritic.com/movie/12-oclock-boys,12 O'Clock Boys,Oscilloscope Laboratories,| Not Rated,76.0,NaN,Lotfy Nathan,"Biography,Documentary","Pug, a young boy growing up on a combative Wes...",NaN,68,4.6,31/01/2014
21,https://www.metacritic.com/movie/12-rounds,12 Rounds,Fox Atomic,| PG-13,108.0,"Ashley Scott,John Cena",Renny Harlin,"Action,Thriller,Crime",NaN,#71MostSharedMovieof2009,38,5.0,27/03/2009
22,https://www.metacritic.com/movie/12-strong,12 Strong,Warner Bros.,| R,130.0,"Austin HÃ©bert,Austin Stowell,Ben O'Toole,Chri...",Nicolai Fuglsig,"Action,Drama,History,War",NaN,"#77MostDiscussedMovieof2018 , #21MostSharedMov...",54,6.3,19/01/2018
23,https://www.metacritic.com/movie/12-years-a-slave,12 Years a Slave,Fox Searchlight Pictures,| R,134.0,"Alfre Woodard,Benedict Cumberbatch,Brad Pitt,C...",Steve McQueen,"Biography,Drama,History","In the pre-Civil War United States, Solomon No...","#1BestMovieof2013 , #17MostDiscussedMovieof201...",96,8.0,18/10/2013
24,https://www.metacritic.com/movie/1208-east-of-...,12:08 East of Bucharest,Tartan,| Unrated,89.0,NaN,Corneliu Porumboiu,"Drama,Comedy,Music",NaN,#51BestMovieof2007,77,7.9,06/06/2007
25,https://www.metacritic.com/movie/127-hours,127 Hours,Fox Searchlight Pictures,| R,94.0,"Amber Tamblyn,James Franco,Kate Mara",Danny Boyle,"Adventure,Biography,Drama,Thriller",127 HOURS is the true story of mountain climbe...,"#23BestMovieof2010 , #26MostDiscussedMovieof20...",82,8.1,05/11/2010
26,https://www.metacritic.com/movie/13,13,Anchor Bay Films,| R,97.0,NaN,GÃ©la Babluani,"Drama,Thriller",It is fiercely organized and ferociously secre...,#61MostSharedMovieof2011,29,5.0,28/10/2011
27,https://www.metacritic.com/movie/13-assassins,13 Assassins,Magnet Releasing,| R,141.0,NaN,Takashi Miike,Action,NaN,"#23BestMovieof2011 , #35MostSharedMovieof2011",84,8.0,29/04/2011
28,https://www.metacritic.com/movie/13-going-on-30,13 Going on 30,Columbia Pictures,| PG-13,98.0,"Jennifer Garner,Judy Greer,Mark Ruffalo",Gary Winick,"Fantasy,Comedy,Romance",It is 1987 and Jenna is a 13-year-old girl on ...,"#72MostDiscussedMovieof2004 , #51MostSharedMov...",57,7.9,23/04/2004
29,https://www.metacritic.com/movie/13-hours-the-...,13 Hours: The Secret Soldiers of Benghazi,Paramount Pictures,| R,144.0,"Alexia Barlier,David Costabile,David Denman,Ja...",Michael Bay,"Action,Drama,Thriller,War",An American Ambassador is killed during an att...,"#51MostDiscussedMovieof2016 , #44MostSharedMov...",48,7.0,15/01/2016
30,https://www.metacritic.com/movie/13-minutes,13 Minutes,Sony Pictures Classics,| R,114.0,"Burghart KlauÃner,Christian Friedel,Cornelia ...",Oliver Hirschbiegel,"Biography,Drama,War",NaN,NaN,58,6.9,30/06/2017
31,https://www.metacritic.com/movie/13-sins,13 Sins,Dimension Films,| R,88.0,NaN,Daniel Stamm,"Thriller,Horror","A bright but meek salesman, drowning in debt a...",NaN,44,6.7,18/04/2014
32,https://www.metacritic.com/movie/13-tzameti,13 Tzameti,Palm Pictures,| Not Rated,93.0,George Babluani,GÃ©la Babluani,"Drama,Thriller,Crime",NaN,NaN,61,7.4,28/07/2006
33,https://www.metacritic.com/movie/13th,13th,Netflix,| TV-MA,100.0,NaN,Ava DuVernay,"Crime,Documentary",NaN,#37BestMovieof2016,83,7.7,07/10/2016
34,https://www.metacritic.com/movie/14-blades,14 Blades,The Weinstein Company,| R,114.0,NaN,Daniel Lee,"Action,Drama,History,Thriller",NaN,NaN,50,NaN,22/08/2014
35,https://www.metacritic.com/movie/1408,1408,Metro-Goldwyn-Mayer (MGM),| PG-13,104.0,"John Cusack,Mary McCormack,Samuel L. Jackson",Mikael HÃ¥fstrÃ¶m,"Thriller,Horror",NaN,"#46MostDiscussedMovieof2007 , #32MostSharedMov...",64,8.2,22/06/2007
36,https://www.metacritic.com/movie/15-minutes,15 Minutes,New Line Cinema,| R,120.0,"Edward Burns,Kelsey Grammer,Robert De Niro",John Herzfeld,"Action,Drama,Thriller,Crime",A thriller seen through an eye-popping new len...,NaN,34,6.2,09/03/2001
37,https://www.metacritic.com/movie/16-blocks,16 Blocks,Warner Bros. Pictures,| PG-13,105.0,"Bruce Willis,David Morse,Mos Def",Richard Donner,"Action,Drama,Thriller,Crime",The story of how two men change -- and change ...,#84MostDiscussedMovieof2006,63,7.8,03/03/2006
38,https://www.metacritic.com/movie/16-years-of-a...,16 Years of Alcohol,Palisades Tartan,| R,102.0,NaN,Richard Jobson,"Drama,Crime",NaN,NaN,57,6.1,18/03/2005
39,https://www.metacritic.com/movie/17-again,17 Again,New Line Cinema,| PG-13,102.0,"Leslie Mann,Matthew Perry,Zac Efron",Burr Steers,"Drama,Comedy,Romance",NaN,"#87MostDiscussedMovieof2009 , #61MostSharedMov...",48,5.9,17/04/2009
40,https://www.metacritic.com/movie/17-blocks,17 Blocks,MTV Documentary Films,| Not Rated,96.0,NaN,Davy Rothbart,Documentary,Footage from two decades of intimate home vide...,#61BestMovieof2019,81,NaN,01/11/2019
41,https://www.metacritic.com/movie/17-girls,17 Girls,Strand Releasing,| Not Rated,86.0,"Esther Garrel,Juliette Darche,Louise Grinberg,...",Delphine Coulin,Drama,NaN,#38MostSharedMovieof2012,61,NaN,21/09/2012
42,https://www.metacritic.com/movie/1911,1911,Well Go,| R,125.0,NaN,Jackie Chan,"Action,Adventure,Drama,History,War",NaN,NaN,37,6.1,07/10/2011
43,https://www.metacritic.com/movie/1917,1917,Universal Pictures,| R,119.0,"Adrian Scarborough,Andrew Scott,Andy Apollo,Be...",Sam Mendes,"Drama,War","At the height of the First World War, two youn...",#18MostDiscussedMovieof2019,78,8.4,25/12/2019
44,https://www.metacritic.com/movie/1922,1922,Netflix,| TV-MA,102.0,"Anna Louise Sargeant,Bob Frazer,Brian d'Arcy J...",Zak Hilditch,"Drama,Mystery,Thriller,Horror,Crime",NaN,NaN,70,6.9,20/10/2017
45,https://www.metacritic.com/movie/1945,1945,Menemsha Films,| Not Rated,91.0,"Ãgi Szirtes,Bence TasnÃ¡di,DÃ³ra Sztarenki,Es...",Ferenc TÃ¶rÃ¶k,Drama,NaN,NaN,73,7.6,01/11/2017
46,https://www.metacritic.com/movie/1971,1971,"Film Collaborative, The",| Not Rated,79.0,NaN,Johanna Hamilton,"History,Thriller,Documentary,News",NaN,NaN,73,7.8,06/02/2015
47,https://www.metacritic.com/movie/1985,1985,Wolfe Releasing,| Not Rated,85.0,"Aidan Langford,Alex Nicole McConnell,Bill Heck...",Yen Tan,Drama,NaN,NaN,71,8.2,26/10/2018
48,https://www.metacritic.com/movie/1br,1BR,NaN,| Not Rated,90.0,"Alan Blumenfeld,Andrea Gabriel,Celeste Sully,C...",David Marmor,"Drama,Thriller,Horror","Sarah tries to start anew in LA, but her neigh...",NaN,56,6.2,24/04/2020
49,https://www.metacritic.com/movie/2-autumns-3-w...,"2 Autumns, 3 Winters",Film Movement,| Not Rated,91.0,NaN,SÃ©bastien Betbeder,Comedy,NaN,NaN,75,NaN,06/06/2014

**Inspection summary:**

Inspection of the Meta dataset shows that most text fields are semantically rich and
will be preserved for later analysis. In Phase 2, only structural corrections are
applied, including date parsing and categorical type assignment.

- `url` (object): Correct, used as an identifier
- `title` (object): Correct text field
- `studio` (object): Categorical variable, should be category
- `rating` (object): Categorical variable, should be category
- `runtime` (float64): Correct numeric type
- `cast` (object): Correct text field, contains missing values
- `director` (object): Correct text field, contains missing values
- `genre` (object): Categorical variable, should be category
- `summary` (object): Correct text field, contains missing values
- `awards` (object): Correct text field, contains many missing values
- `meta_score` (int64): Correct numeric type
- `user_score` (float64): Correct numeric type
- `release_date` (object): Should be datetime

### 2.2 Data Type and Basic Semantic Corrections

Based on the inspection, we apply the following corrections:
- Convert release_date to datetime
- Convert categorical variables to category type
- Preserve text fields as object without semantic alteration

In [51]:
# Convert release_date to datetime
meta_df['release_date'] = pd.to_datetime(
    meta_df['release_date'], errors='coerce'
)

# Convert categorical columns to category
for col in ['studio', 'rating', 'genre']:
    meta_df[col] = meta_df[col].astype('category')

### 2.3 Post-correction Verification

We re-inspect a sample of the data to confirm that the corrections
have been applied correctly and that no unintended changes were introduced.

In [52]:
# Verify sample rows
meta_df.head(50)

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,meta_score,user_score,release_date
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-01-06
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-11-03
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-01-12
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,NaT
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,NaT
5,https://www.metacritic.com/movie/100-streets,100 Streets,Samuel Goldwyn Films,NaN,93.0,NaN,Jim O'Hanlon,Drama,NaN,NaN,44,6.1,NaT
6,https://www.metacritic.com/movie/1000-times-go...,"1,000 Times Good Night",Film Movement,| Not Rated,117.0,NaN,Erik Poppe,Drama,NaN,NaN,57,6.8,NaT
7,https://www.metacritic.com/movie/10000-bc,"10,000 BC",Warner Bros. Pictures,| PG-13,109.0,"Camilla Belle,Marco Khan,Steven Strait",Roland Emmerich,"Adventure,Drama,Fantasy",NaN,"#23MostDiscussedMovieof2008 , #27MostSharedMov...",34,4.6,2008-07-03
8,https://www.metacritic.com/movie/10000-km,"10,000 km",Broad Green Pictures,| R,99.0,NaN,Carlos Marques-Marcet,"Drama,Comedy,Romance","Two people in love, two apartments - one in Ba...",NaN,75,7.4,2015-10-07
9,https://www.metacritic.com/movie/1001-grams,1001 Grams,Kino Lorber,| Not Rated,93.0,NaN,Bent Hamer,Drama,When Norwegian scientist Marie attends a semin...,NaN,65,NaN,2015-08-05
10,https://www.metacritic.com/movie/101-reykjavik,ReykjavÃ­k,Menemsha Entertainment,| Not Rated,88.0,"Hilmir SnÃ¦r GuÃ°nason,Victoria Abril",Baltasar KormÃ¡kur,"Comedy,Romance",A young man's sexual impulses go haywire when ...,NaN,68,5.4,NaT
11,https://www.metacritic.com/movie/102-dalmatians,102 Dalmatians,Buena Vista Pictures,| G,100.0,"GÃ©rard Depardieu,Glenn Close",Kevin Lima,"Comedy,Family",Just when it seemed safe to come out of the ke...,#73MostDiscussedMovieof2000,35,5.1,NaT
12,https://www.metacritic.com/movie/10th-wolf,10th & Wolf,THINKFilm,| R,107.0,"Brad Renfro,Giovanni Ribisi,James Marsden",Robert Moresco,"Drama,Mystery,Thriller,Crime",A Philadelphia mob war is the backdrop of 10th...,NaN,36,6.7,NaT
13,https://www.metacritic.com/movie/11-flowers,11 Flowers,First Run Features,| Not Rated,110.0,NaN,Xiaoshuai Wang,Drama,When 11-year-old Wang is selected to lead his ...,NaN,71,NaN,NaT
14,https://www.metacritic.com/movie/11-minutes,11 Minutes,IFC Films,| Not Rated,81.0,NaN,Jerzy Skolimowski,"Drama,Thriller","In a city square in Warsaw, a sleazy film dire...",NaN,51,7.5,2016-08-04
15,https://www.metacritic.com/movie/11816,11/8/16,The Orchard,| TV-MA,104.0,Abby Linne,Alison Klayman,Documentary,"On the morning of Election Day 2016, Americans...",NaN,62,NaN,2017-03-11
16,https://www.metacritic.com/movie/12,12,Sony Pictures Classics,| PG-13,159.0,"Apti Magamaev,Sergei Makovetsky,Sergey Garmash",Nikita Mikhalkov,"Drama,Thriller,Crime,War",NaN,"#97BestMovieof2009 , #18MostSharedMovieof2009",72,7.4,2009-04-03
17,https://www.metacritic.com/movie/12-12-12,12-12-12,"Weinstein Company, The",| R,105.0,NaN,Amir Bar-Lev,Documentary,A behind-the-scenes look at the televised bene...,NaN,54,NaN,NaT
18,https://www.metacritic.com/movie/12-hour-shift,12 Hour Shift,Magnet Releasing,| Not Rated,87.0,"Angela Bettis,Brooke Seguin,Chloe Farnworth,Da...",Brea Grant,"Thriller,Horror,Comedy",NaN,NaN,63,5.8,2020-02-10
19,https://www.metacritic.com/movie/12-mighty-orp...,12 Mighty Orphans,Sony Pictures Classics,| PG-13,118.0,"Carlson Young,Jacob Lofland,Jake Austin Walker...",Ty Roberts,"History,Sport",NaN,NaN,44,6.6,2021-11-06
20,https://www.metacritic.com/movie/12-oclock-boys,12 O'Clock Boys,Oscilloscope Laboratories,| Not Rated,76.0,NaN,Lotfy Nathan,"Biography,Documentary","Pug, a young boy growing up on a combative Wes...",NaN,68,4.6,NaT
21,https://www.metacritic.com/movie/12-rounds,12 Rounds,Fox Atomic,| PG-13,108.0,"Ashley Scott,John Cena",Renny Harlin,"Action,Thriller,Crime",NaN,#71MostSharedMovieof2009,38,5.0,NaT
22,https://www.metacritic.com/movie/12-strong,12 Strong,Warner Bros.,| R,130.0,"Austin HÃ©bert,Austin Stowell,Ben O'Toole,Chri...",Nicolai Fuglsig,"Action,Drama,History,War",NaN,"#77MostDiscussedMovieof2018 , #21MostSharedMov...",54,6.3,NaT
23,https://www.metacritic.com/movie/12-years-a-slave,12 Years a Slave,Fox Searchlight Pictures,| R,134.0,"Alfre Woodard,Benedict Cumberbatch,Brad Pitt,C...",Steve McQueen,"Biography,Drama,History","In the pre-Civil War United States, Solomon No...","#1BestMovieof2013 , #17MostDiscussedMovieof201...",96,8.0,NaT
24,https://www.metacritic.com/movie/1208-east-of-...,12:08 East of Bucharest,Tartan,| Unrated,89.0,NaN,Corneliu Porumboiu,"Drama,Comedy,Music",NaN,#51BestMovieof2007,77,7.9,2007-06-06
25,https://www.metacritic.com/movie/127-hours,127 Hours,Fox Searchlight Pictures,| R,94.0,"Amber Tamblyn,James Franco,Kate Mara",Danny Boyle,"Adventure,Biography,Drama,Thriller",127 HOURS is the true story of mountain climbe...,"#23BestMovieof2010 , #26MostDiscussedMovieof20...",82,8.1,2010-05-11
26,https://www.metacritic.com/movie/13,13,Anchor Bay Films,| R,97.0,NaN,GÃ©la Babluani,"Drama,Thriller",It is fiercely organized and ferociously secre...,#61MostSharedMovieof2011,29,5.0,NaT
27,https://www.metacritic.com/movie/13-assassins,13 Assassins,Magnet Releasing,| R,141.0,NaN,Takashi Miike,Action,NaN,"#23BestMovieof2011 , #35MostSharedMovieof2011",84,8.0,NaT
28,https://www.metacritic.com/movie/13-going-on-30,13 Going on 30,Columbia Pictures,| PG-13,98.0,"Jennifer Garner,Judy Greer,Mark Ruffalo",Gary Winick,"Fantasy,Comedy,Romance",It is 1987 and Jenna is a 13-year-old girl on ...,"#72MostDiscussedMovieof2004 , #51MostSharedMov...",57,7.9,NaT
29,https://www.metacritic.com/movie/13-hours-the-...,13 Hours: The Secret Soldiers of Benghazi,Paramount Pictures,| R,144.0,"Alexia Barlier,David Costabile,David Denman,Ja...",Michael Bay,"Action,Drama,Thriller,War",An American Ambassador is killed during an att...,"#51MostDiscussedMovieof2016 , #44MostSharedMov...",48,7.0,NaT
30,https://www.metacritic.com/movie/13-minutes,13 Minutes,Sony Pictures Classics,| R,114.0,"Burghart KlauÃner,Christian Friedel,Cornelia ...",Oliver Hirschbiegel,"Biography,Drama,War",NaN,NaN,58,6.9,NaT
31,https://www.metacritic.com/movie/13-sins,13 Sins,Dimension Films,| R,88.0,NaN,Daniel Stamm,"Thriller,Horror","A bright but meek salesman, drowning in debt a...",NaN,44,6.7,NaT
32,https://www.metacritic.com/movie/13-tzameti,13 Tzameti,Palm Pictures,| Not Rated,93.0,George Babluani,GÃ©la Babluani,"Drama,Thriller,Crime",NaN,NaN,61,7.4,NaT
33,https://www.metacritic.com/movie/13th,13th,Netflix,| TV-MA,100.0,NaN,Ava DuVernay,"Crime,Documentary",NaN,#37BestMovieof2016,83,7.7,2016-07-10
34,https://www.metacritic.com/movie/14-blades,14 Blades,The Weinstein Company,| R,114.0,NaN,Daniel Lee,"Action,Drama,History,Thriller",NaN,NaN,50,NaN,NaT
35,https://www.metacritic.com/movie/1408,1408,Metro-Goldwyn-Mayer (MGM),| PG-13,104.0,"John Cusack,Mary McCormack,Samuel L. Jackson",Mikael HÃ¥fstrÃ¶m,"Thriller,Horror",NaN,"#46MostDiscussedMovieof2007 , #32MostSharedMov...",64,8.2,NaT
36,https://www.metacritic.com/movie/15-minutes,15 Minutes,New Line Cinema,| R,120.0,"Edward Burns,Kelsey Grammer,Robert De Niro",John Herzfeld,"Action,Drama,Thriller,Crime",A thriller seen through an eye-popping new len...,NaN,34,6.2,2001-09-03
37,https://www.metacritic.com/movie/16-blocks,16 Blocks,Warner Bros. Pictures,| PG-13,105.0,"Bruce Willis,David Morse,Mos Def",Richard Donner,"Action,Drama,Thriller,Crime",The story of how two men change -- and change ...,#84MostDiscussedMovieof2006,63,7.8,2006-03-03
38,https://www.metacritic.com/movie/16-years-of-a...,16 Years of Alcohol,Palisades Tartan,| R,102.0,NaN,Richard Jobson,"Drama,Crime",NaN,NaN,57,6.1,NaT
39,https://www.metacritic.com/movie/17-again,17 Again,New Line Cinema,| PG-13,102.0,"Leslie Mann,Matthew Perry,Zac Efron",Burr Steers,"Drama,Comedy,Romance",NaN,"#87MostDiscussedMovieof2009 , #61MostSharedMov...",48,5.9,NaT
40,https://www.metacritic.com/movie/17-blocks,17 Blocks,MTV Documentary Films,| Not Rated,96.0,NaN,Davy Rothbart,Documentary,Footage from two decades of intimate home vide...,#61BestMovieof2019,81,NaN,2019-01-11
41,https://www.metacritic.com/movie/17-girls,17 Girls,Strand Releasing,| Not Rated,86.0,"Esther Garrel,Juliette Darche,Louise Grinberg,...",Delphine Coulin,Drama,NaN,#38MostSharedMovieof2012,61,NaN,NaT
42,https://www.metacritic.com/movie/1911,1911,Well Go,| R,125.0,NaN,Jackie Chan,"Action,Adventure,Drama,History,War",NaN,NaN,37,6.1,2011-07-10
43,https://www.metacritic.com/movie/1917,1917,Universal Pictures,| R,119.0,"Adrian Scarborough,Andrew Scott,Andy Apollo,Be...",Sam Mendes,"Drama,War","At the height of the First World War, two youn...",#18MostDiscussedMovieof2019,78,8.4,NaT
44,https://www.metacritic.com/movie/1922,1922,Netflix,| TV-MA,102.0,"Anna Louise Sargeant,Bob Frazer,Brian d'Arcy J...",Zak Hilditch,"Drama,Mystery,Thriller,Horror,Crime",NaN,NaN,70,6.9,NaT
45,https://www.metacritic.com/movie/1945,1945,Menemsha Films,| Not Rated,91.0,"Ãgi Szirtes,Bence TasnÃ¡di,DÃ³ra Sztarenki,Es...",Ferenc TÃ¶rÃ¶k,Drama,NaN,NaN,73,7.6,2017-01-11
46,https://www.metacritic.com/movie/1971,1971,"Film Collaborative, The",| Not Rated,79.0,NaN,Johanna Hamilton,"History,Thriller,Documentary,News",NaN,NaN,73,7.8,2015-06-02
47,https://www.metacritic.com/movie/1985,1985,Wolfe Releasing,| Not Rated,85.0,"Aidan Langford,Alex Nicole McConnell,Bill Heck...",Yen Tan,Drama,NaN,NaN,71,8.2,NaT
48,https://www.metacritic.com/movie/1br,1BR,NaN,| Not Rated,90.0,"Alan Blumenfeld,Andrea Gabriel,Celeste Sully,C...",David Marmor,"Drama,Thriller,Horror","Sarah tries to start anew in LA, but her neigh...",NaN,56,6.2,NaT
49,https://www.metacritic.com/movie/2-autumns-3-w...,"2 Autumns, 3 Winters",Film Movement,| Not Rated,91.0,NaN,SÃ©bastien Betbeder,Comedy,NaN,NaN,75,NaN,2014-06-06

## Stage 3: Sales

This stage focuses on inspecting and correcting data types and basic structural issues
in the Sales dataset. This table contains financial and operational information and
exhibits a high proportion of missing values, requiring careful and conservative
cleaning decisions.

In [53]:
# Inspect data types
print(sales_df.dtypes)

# Inspect sample rows
sales_df.head(50)

year                     int64
release_date            object
title                   object
genre                   object
intl_box_office        float64
dom_box_office         float64
global_box_office      float64
production_budget      float64
opening_weekend        float64
theatre_count          float64
avg_run_per_theatre    float64
runtime                float64
keywords                object
creative_type           object
url                     object
dtype: object

,year,release_date,title,genre,intl_box_office,dom_box_office,global_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...
5,2002,June 21st,Zig Zag,NaN,NaN,1649.0,NaN,NaN,1649.0,1.0,1.0,NaN,NaN,NaN,https://www.the-numbers.com/movie/Zig-Zag
6,2002,May 10th,TakhtÃƒÂ© siah,Drama,NaN,21324.0,NaN,NaN,1500.0,5.0,2.0,NaN,Foreign Language,NaN,https://www.the-numbers.com/movie/Takhte-siah
7,2009,January 2nd,"Angry Monk: Reflections on Tibet, The",Documentary,NaN,2125.0,NaN,NaN,2125.0,1.0,1.0,NaN,NaN,Factual,https://www.the-numbers.com/movie/Angry-Monk-R...
8,2002,June 7th,30 Years to Life,Comedy,NaN,99023.0,NaN,NaN,3376.0,1.0,3.3,NaN,NaN,NaN,https://www.the-numbers.com/movie/30-Years-to-...
9,2008,January 2nd,The Killing of John Lennon,Drama,NaN,6975.0,NaN,NaN,3077.0,1.0,3.0,NaN,NaN,Dramatization,https://www.the-numbers.com/movie/Killing-of-J...
10,2008,January 18th,Mad Money,Comedy,4375214.0,20668843.0,25044057.0,22000000.0,7736452.0,2470.0,3.4,104.0,Heist,Contemporary Fiction,https://www.the-numbers.com/movie/Mad-Money
11,2008,January 18th,Little Chenier,Drama,NaN,87939.0,NaN,NaN,37318.0,17.0,1.7,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Little-Chenier
12,2008,February 1st,Over Her Dead Body,Comedy,14025947.0,7570127.0,21596074.0,10000000.0,4025115.0,1977.0,2.3,95.0,Haunting,Fantasy,https://www.the-numbers.com/movie/Over-Her-Dea...
13,2008,February 15th,O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias,Drama,1800000.0,807117.0,2607117.0,NaN,80655.0,18.0,11.2,103.0,Soccer,Historical Fiction,https://www.the-numbers.com/movie/Ano-em-Que-M...
14,2008,February 15th,120,Drama,1334204.0,NaN,1334204.0,NaN,NaN,NaN,NaN,114.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/120-(Turkey)
15,2008,February 29th,The Other Boleyn Girl,Drama,51455013.0,26814957.0,78269970.0,40000000.0,8203061.0,1166.0,5.9,115.0,Royalty,Historical Fiction,https://www.the-numbers.com/movie/Other-Boleyn...
16,2008,February 29th,A Lawyer Walks into a Bar,Documentary,NaN,5202.0,NaN,NaN,985.0,1.0,10.0,NaN,NaN,Factual,https://www.the-numbers.com/movie/Lawyer-Walks...
17,2008,March 8th,La Rondine,Concert/Performance,NaN,49088.0,NaN,NaN,NaN,NaN,NaN,106.0,TV Movie,Factual,https://www.the-numbers.com/movie/Rondine-La
18,2011,December 30th,Jodaeiye Nader az Simin,Drama,17327677.0,7098492.0,24426169.0,800000.0,59481.0,3.0,7.0,123.0,Dysfunctional Family,Contemporary Fiction,https://www.the-numbers.com/movie/Jodaeiye-Nad...
19,2011,December 28th,Pariah,Drama,NaN,769552.0,NaN,NaN,48579.0,4.0,6.8,86.0,LGBTQ+,Contemporary Fiction,https://www.the-numbers.com/movie/Pariah-(2011)
20,2011,December 25th,War Horse,Drama,76932170.0,79883359.0,156815529.0,70000000.0,7515402.0,2376.0,6.3,146.0,World War I,Contemporary Fiction,https://www.the-numbers.com/movie/War-Horse
21,2011,April 6th,Habemus Papam,Comedy,9917173.0,486902.0,10404075.0,NaN,31368.0,3.0,6.1,104.0,Religious,Contemporary Fiction,https://www.the-numbers.com/movie/Habemus-Papam
22,2011,December 29th,Ivan Tsarevich i Seryy Volk,Action,25047727.0,NaN,25047727.0,NaN,NaN,NaN,NaN,75.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Ivan-Tsarevi...
23,2011,December 28th,El Sicario Room 164,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,Government Corruption,Factual,https://www.the-numbers.com/movie/Sicario-Room...
24,2011,December 25th,Extremely Loud and Incredibly Close,Drama,23400000.0,31847881.0,55247881.0,40000000.0,72348.0,6.0,4.1,129.0,11-Sep,Historical Fiction,https://www.the-numbers.com/movie/Extremely-Lo...
25,2011,December 30th,Angels Crest,Drama,1205.0,832.0,2037.0,NaN,407.0,1.0,1.0,96.0,Life in a Small Town,Contemporary Fiction,https://www.the-numbers.com/movie/Angels-Crest
26,2011,December 28th,Paranormal Xperience,Horror,2812739.0,NaN,2812739.0,NaN,NaN,NaN,NaN,90.0,3-D,Contemporary Fiction,https://www.the-numbers.com/movie/Paranormal-X...
27,2011,December 25th,The Darkest Hour,Action,41388221.0,21443494.0,62831715.0,34800000.0,2993519.0,2324.0,3.7,89.0,Alien Invasion,Science Fiction,https://www.the-numbers.com/movie/Darkest-Hour...
28,2011,December 23rd,Miss Minoes,Adventure,NaN,10189.0,NaN,NaN,1901.0,3.0,1.5,NaN,NaN,Kids Fiction,https://www.the-numbers.com/movie/Miss-Minoes
29,2011,November 26th,We Bought a Zoo,Drama,43104523.0,75624550.0,118729073.0,50000000.0,9360434.0,3117.0,5.9,124.0,Animal Lead,Dramatization,https://www.the-numbers.com/movie/We-Bought-a-Zoo
30,2014,November 21st,Minuscule - La vallÃƒÂ©e des fourmis perdues,Adventure,1058457.0,NaN,1058457.0,NaN,NaN,NaN,NaN,89.0,NaN,Kids Fiction,https://www.the-numbers.com/movie/Minuscule-La...
31,2011,May 11th,Kiseki,Drama,766350.0,145808.0,912158.0,NaN,10919.0,5.0,7.3,128.0,Relationships Gone Wrong,Contemporary Fiction,https://www.the-numbers.com/movie/Kiseki
32,2011,December 23rd,In The Land of Blood and Honey,Drama,205316.0,303877.0,509193.0,13000000.0,18854.0,3.0,5.1,NaN,Actors Making Their Directorial Debut,Historical Fiction,https://www.the-numbers.com/movie/In-The-Land-...
33,2011,December 23rd,Prince of the Himalayas,Drama,NaN,9178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Historical Fiction,https://www.the-numbers.com/movie/Prince-of-th...
34,2011,December 22nd,Don 2,Action,30378610.0,3674480.0,34053090.0,NaN,1673921.0,161.0,2.9,148.0,3-D,Contemporary Fiction,https://www.the-numbers.com/movie/Don-2
35,2014,December 12th,We Are the Giant,Documentary,NaN,1088.0,NaN,NaN,1088.0,2.0,1.0,90.0,Arab Spring,Factual,https://www.the-numbers.com/movie/We-Are-the-G...
36,2014,December 31st,Wang Pai,Drama,4590000.0,NaN,4590000.0,NaN,NaN,NaN,NaN,90.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Wang-Pai-(Ch...
37,2015,July 24th,The Young Kieslowski,Romantic Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Young-Kieslo...
38,2015,June 10th,Last Cab to Darwin,Drama,5786944.0,34193.0,5821137.0,NaN,620.0,1.0,5.3,123.0,Terminal Illness,Contemporary Fiction,https://www.the-numbers.com/movie/Last-Cab-to-...
39,2014,December 12th,Cong cong na nian,Drama,93470000.0,566853.0,94036853.0,NaN,NaN,NaN,NaN,119.0,Set in China,Historical Fiction,https://www.the-numbers.com/movie/Cong-cong-na...
40,2015,July 31st,Ghadi,Comedy,70149.0,NaN,70149.0,NaN,NaN,NaN,NaN,100.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Ghadi-(Lebanon)
41,2015,July 31st,Fair Play,Drama,8747.0,NaN,8747.0,NaN,NaN,NaN,NaN,100.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Fair-Play-(C...
42,2015,August 14th,Meru,Documentary,16592.0,2334228.0,2350820.0,NaN,91279.0,7.0,4.4,89.0,Mountain Climbing,Factual,https://www.the-numbers.com/movie/Meru
43,2015,August 21st,Station to Station,Documentary,1036.0,9494.0,10530.0,NaN,9494.0,1.0,1.0,70.0,Trains,Factual,https://www.the-numbers.com/movie/Station-to-S...
44,2015,August 14th,Karachi se Lahore,Comedy,17721.0,NaN,17721.0,1000000.0,NaN,NaN,NaN,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Karachi-se-L...
45,2015,December 4th,Atrapa la bandera,Adventure,21131406.0,NaN,21131406.0,NaN,NaN,NaN,NaN,NaN,NaN,Kids Fiction,https://www.the-numbers.com/movie/Atrapa-la-ba...
46,2015,September 10th,Alma,Romantic Comedy,567607.0,NaN,567607.0,NaN,NaN,NaN,NaN,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Alma
47,2015,August 28th,"Boca Juniors 3D, la pelÃƒÂ­cula",Documentary,2171383.0,NaN,2171383.0,NaN,NaN,NaN,NaN,NaN,Soccer,Factual,https://www.the-numbers.com/movie/Boca-Juniors...
48,2015,September 18th,Life of Josutty,Comedy,7870.0,NaN,7870.0,NaN,NaN,NaN,NaN,166.0,Set in India,Contemporary Fiction,https://www.the-numbers.com/movie/Life-of-Josu...
49,2015,September 9th,Welcome to Leith,Documentary,381.0,36010.0,36391.0,NaN,3707.0,1.0,4.4,86.0,Bigotry,Factual,https://www.the-numbers.com/movie/Welcome-to-L...

**Inspection summary:**

Inspection of the Sales dataset shows that the release_date column contains
inconsistent and non-standard values (e.g., partial dates and descriptive text).
To avoid introducing errors, the release_date column is preserved as text and
the year column is retained as the primary temporal reference in Phase 2.


- `year` (int64): Correct numeric type, primary temporal reference
- `release_date` (object / datetime64): Contains many missing or invalid values
- `title` (object): Correct text field
- `genre` (object): Categorical variable, should be category
- `intl_box_office` (float64): Numeric, contains many missing values
- `dom_box_office` (float64): Numeric, contains many missing values
- `global_box_office` (float64): Numeric, contains many missing values
- `production_budget` (float64): Numeric, high proportion of missing values
- `opening_weekend` (float64): Numeric, many missing values
- `theatre_count` (float64): Numeric, many missing values
- `avg_run_per_theatre` (float64): Numeric, many missing values
- `runtime` (float64): Numeric, partially missing
- `keywords` (object): Free-text field
- `creative_type` (object): Categorical variable, should be category
- `url` (object): Correct, used as an identifier

### 3.2 Data Type and Structural Corrections

Based on the inspection, we apply conservative corrections:
- Convert categorical variables to category type
- Retain numeric columns as floats to preserve missing values
- Preserve year as the primary temporal reference
- Avoid reconstructing release_date in Phase 2

In [54]:
# Convert categorical columns
sales_df['genre'] = sales_df['genre'].astype('category')
sales_df['creative_type'] = sales_df['creative_type'].astype('category')

### 3.3 Post-correction Verification

We re-inspect the data types and a sample of the data to confirm that
the corrections have been applied correctly and that no unintended changes
were introduced.

In [55]:
# Verify sample rows
sales_df.head(50)

,year,release_date,title,genre,intl_box_office,dom_box_office,global_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...
5,2002,June 21st,Zig Zag,NaN,NaN,1649.0,NaN,NaN,1649.0,1.0,1.0,NaN,NaN,NaN,https://www.the-numbers.com/movie/Zig-Zag
6,2002,May 10th,TakhtÃƒÂ© siah,Drama,NaN,21324.0,NaN,NaN,1500.0,5.0,2.0,NaN,Foreign Language,NaN,https://www.the-numbers.com/movie/Takhte-siah
7,2009,January 2nd,"Angry Monk: Reflections on Tibet, The",Documentary,NaN,2125.0,NaN,NaN,2125.0,1.0,1.0,NaN,NaN,Factual,https://www.the-numbers.com/movie/Angry-Monk-R...
8,2002,June 7th,30 Years to Life,Comedy,NaN,99023.0,NaN,NaN,3376.0,1.0,3.3,NaN,NaN,NaN,https://www.the-numbers.com/movie/30-Years-to-...
9,2008,January 2nd,The Killing of John Lennon,Drama,NaN,6975.0,NaN,NaN,3077.0,1.0,3.0,NaN,NaN,Dramatization,https://www.the-numbers.com/movie/Killing-of-J...
10,2008,January 18th,Mad Money,Comedy,4375214.0,20668843.0,25044057.0,22000000.0,7736452.0,2470.0,3.4,104.0,Heist,Contemporary Fiction,https://www.the-numbers.com/movie/Mad-Money
11,2008,January 18th,Little Chenier,Drama,NaN,87939.0,NaN,NaN,37318.0,17.0,1.7,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Little-Chenier
12,2008,February 1st,Over Her Dead Body,Comedy,14025947.0,7570127.0,21596074.0,10000000.0,4025115.0,1977.0,2.3,95.0,Haunting,Fantasy,https://www.the-numbers.com/movie/Over-Her-Dea...
13,2008,February 15th,O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias,Drama,1800000.0,807117.0,2607117.0,NaN,80655.0,18.0,11.2,103.0,Soccer,Historical Fiction,https://www.the-numbers.com/movie/Ano-em-Que-M...
14,2008,February 15th,120,Drama,1334204.0,NaN,1334204.0,NaN,NaN,NaN,NaN,114.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/120-(Turkey)
15,2008,February 29th,The Other Boleyn Girl,Drama,51455013.0,26814957.0,78269970.0,40000000.0,8203061.0,1166.0,5.9,115.0,Royalty,Historical Fiction,https://www.the-numbers.com/movie/Other-Boleyn...
16,2008,February 29th,A Lawyer Walks into a Bar,Documentary,NaN,5202.0,NaN,NaN,985.0,1.0,10.0,NaN,NaN,Factual,https://www.the-numbers.com/movie/Lawyer-Walks...
17,2008,March 8th,La Rondine,Concert/Performance,NaN,49088.0,NaN,NaN,NaN,NaN,NaN,106.0,TV Movie,Factual,https://www.the-numbers.com/movie/Rondine-La
18,2011,December 30th,Jodaeiye Nader az Simin,Drama,17327677.0,7098492.0,24426169.0,800000.0,59481.0,3.0,7.0,123.0,Dysfunctional Family,Contemporary Fiction,https://www.the-numbers.com/movie/Jodaeiye-Nad...
19,2011,December 28th,Pariah,Drama,NaN,769552.0,NaN,NaN,48579.0,4.0,6.8,86.0,LGBTQ+,Contemporary Fiction,https://www.the-numbers.com/movie/Pariah-(2011)
20,2011,December 25th,War Horse,Drama,76932170.0,79883359.0,156815529.0,70000000.0,7515402.0,2376.0,6.3,146.0,World War I,Contemporary Fiction,https://www.the-numbers.com/movie/War-Horse
21,2011,April 6th,Habemus Papam,Comedy,9917173.0,486902.0,10404075.0,NaN,31368.0,3.0,6.1,104.0,Religious,Contemporary Fiction,https://www.the-numbers.com/movie/Habemus-Papam
22,2011,December 29th,Ivan Tsarevich i Seryy Volk,Action,25047727.0,NaN,25047727.0,NaN,NaN,NaN,NaN,75.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Ivan-Tsarevi...
23,2011,December 28th,El Sicario Room 164,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,Government Corruption,Factual,https://www.the-numbers.com/movie/Sicario-Room...
24,2011,December 25th,Extremely Loud and Incredibly Close,Drama,23400000.0,31847881.0,55247881.0,40000000.0,72348.0,6.0,4.1,129.0,11-Sep,Historical Fiction,https://www.the-numbers.com/movie/Extremely-Lo...
25,2011,December 30th,Angels Crest,Drama,1205.0,832.0,2037.0,NaN,407.0,1.0,1.0,96.0,Life in a Small Town,Contemporary Fiction,https://www.the-numbers.com/movie/Angels-Crest
26,2011,December 28th,Paranormal Xperience,Horror,2812739.0,NaN,2812739.0,NaN,NaN,NaN,NaN,90.0,3-D,Contemporary Fiction,https://www.the-numbers.com/movie/Paranormal-X...
27,2011,December 25th,The Darkest Hour,Action,41388221.0,21443494.0,62831715.0,34800000.0,2993519.0,2324.0,3.7,89.0,Alien Invasion,Science Fiction,https://www.the-numbers.com/movie/Darkest-Hour...
28,2011,December 23rd,Miss Minoes,Adventure,NaN,10189.0,NaN,NaN,1901.0,3.0,1.5,NaN,NaN,Kids Fiction,https://www.the-numbers.com/movie/Miss-Minoes
29,2011,November 26th,We Bought a Zoo,Drama,43104523.0,75624550.0,118729073.0,50000000.0,9360434.0,3117.0,5.9,124.0,Animal Lead,Dramatization,https://www.the-numbers.com/movie/We-Bought-a-Zoo
30,2014,November 21st,Minuscule - La vallÃƒÂ©e des fourmis perdues,Adventure,1058457.0,NaN,1058457.0,NaN,NaN,NaN,NaN,89.0,NaN,Kids Fiction,https://www.the-numbers.com/movie/Minuscule-La...
31,2011,May 11th,Kiseki,Drama,766350.0,145808.0,912158.0,NaN,10919.0,5.0,7.3,128.0,Relationships Gone Wrong,Contemporary Fiction,https://www.the-numbers.com/movie/Kiseki
32,2011,December 23rd,In The Land of Blood and Honey,Drama,205316.0,303877.0,509193.0,13000000.0,18854.0,3.0,5.1,NaN,Actors Making Their Directorial Debut,Historical Fiction,https://www.the-numbers.com/movie/In-The-Land-...
33,2011,December 23rd,Prince of the Himalayas,Drama,NaN,9178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Historical Fiction,https://www.the-numbers.com/movie/Prince-of-th...
34,2011,December 22nd,Don 2,Action,30378610.0,3674480.0,34053090.0,NaN,1673921.0,161.0,2.9,148.0,3-D,Contemporary Fiction,https://www.the-numbers.com/movie/Don-2
35,2014,December 12th,We Are the Giant,Documentary,NaN,1088.0,NaN,NaN,1088.0,2.0,1.0,90.0,Arab Spring,Factual,https://www.the-numbers.com/movie/We-Are-the-G...
36,2014,December 31st,Wang Pai,Drama,4590000.0,NaN,4590000.0,NaN,NaN,NaN,NaN,90.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Wang-Pai-(Ch...
37,2015,July 24th,The Young Kieslowski,Romantic Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Young-Kieslo...
38,2015,June 10th,Last Cab to Darwin,Drama,5786944.0,34193.0,5821137.0,NaN,620.0,1.0,5.3,123.0,Terminal Illness,Contemporary Fiction,https://www.the-numbers.com/movie/Last-Cab-to-...
39,2014,December 12th,Cong cong na nian,Drama,93470000.0,566853.0,94036853.0,NaN,NaN,NaN,NaN,119.0,Set in China,Historical Fiction,https://www.the-numbers.com/movie/Cong-cong-na...
40,2015,July 31st,Ghadi,Comedy,70149.0,NaN,70149.0,NaN,NaN,NaN,NaN,100.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Ghadi-(Lebanon)
41,2015,July 31st,Fair Play,Drama,8747.0,NaN,8747.0,NaN,NaN,NaN,NaN,100.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Fair-Play-(C...
42,2015,August 14th,Meru,Documentary,16592.0,2334228.0,2350820.0,NaN,91279.0,7.0,4.4,89.0,Mountain Climbing,Factual,https://www.the-numbers.com/movie/Meru
43,2015,August 21st,Station to Station,Documentary,1036.0,9494.0,10530.0,NaN,9494.0,1.0,1.0,70.0,Trains,Factual,https://www.the-numbers.com/movie/Station-to-S...
44,2015,August 14th,Karachi se Lahore,Comedy,17721.0,NaN,17721.0,1000000.0,NaN,NaN,NaN,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Karachi-se-L...
45,2015,December 4th,Atrapa la bandera,Adventure,21131406.0,NaN,21131406.0,NaN,NaN,NaN,NaN,NaN,NaN,Kids Fiction,https://www.the-numbers.com/movie/Atrapa-la-ba...
46,2015,September 10th,Alma,Romantic Comedy,567607.0,NaN,567607.0,NaN,NaN,NaN,NaN,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Alma
47,2015,August 28th,"Boca Juniors 3D, la pelÃƒÂ­cula",Documentary,2171383.0,NaN,2171383.0,NaN,NaN,NaN,NaN,NaN,Soccer,Factual,https://www.the-numbers.com/movie/Boca-Juniors...
48,2015,September 18th,Life of Josutty,Comedy,7870.0,NaN,7870.0,NaN,NaN,NaN,NaN,166.0,Set in India,Contemporary Fiction,https://www.the-numbers.com/movie/Life-of-Josu...
49,2015,September 9th,Welcome to Leith,Documentary,381.0,36010.0,36391.0,NaN,3707.0,1.0,4.4,86.0,Bigotry,Factual,https://www.the-numbers.com/movie/Welcome-to-L...

# Phase 3: Relationships and Dataset Integration

Phase 3 focuses on identifying, validating, and defining relationships between
the datasets prepared in Phases 1 and 2. Before performing any merges, we analyze
key consistency, relationship cardinality, and potential sources of duplication
or data loss.

This phase ensures that dataset integration is performed deliberately and
correctly, rather than implicitly or through trial and error.

## Stage 0: Meta ↔ Sales Relationship Feasibility

The Sales dataset originates from a different source and does not share a
common URL structure with Meta. To evaluate whether a relationship can exist,
we perform a title-based intersection analysis without merging any data.

Meta is treated as the anchor table.

### 0.1 Title-based Intersection (NO MERGE)

Movie titles are normalized and compared to identify Meta movies that
also appear in the Sales dataset.

In [56]:
# Normalize titles
meta_titles = (
    meta_df['title']
    .astype(str)
    .str.lower()
    .str.strip()
)

sales_titles = (
    sales_df['title']
    .astype(str)
    .str.lower()
    .str.strip()
)

# Create Sales title set
sales_title_set = set(sales_titles.dropna())

# Identify Meta titles that exist in Sales
meta_in_sales_mask = meta_titles.isin(sales_title_set)

# Summary
print("Meta movies with a Sales match:", meta_in_sales_mask.sum())
print(
    "Percentage of Meta movies covered by Sales:",
    f"{meta_in_sales_mask.mean() * 100:.2f}%"
)

# Inspect intersecting Meta rows
meta_df.loc[meta_in_sales_mask, ['title', 'release_date']].head(20)

Meta movies with a Sales match: 8643
Percentage of Meta movies covered by Sales: 76.06%

                                        title release_date
1                         10 Cloverfield Lane   2016-11-03
3                                    10 Years          NaT
4                            100 Bloody Acres          NaT
5                                 100 Streets          NaT
8                                   10,000 km   2015-10-07
9                                  1001 Grams   2015-08-05
11                             102 Dalmatians          NaT
12                                10th & Wolf          NaT
16                                         12   2009-04-03
18                              12 Hour Shift   2020-02-10
19                          12 Mighty Orphans   2021-11-06
21                                  12 Rounds          NaT
22                                  12 Strong          NaT
23                           12 Years a Slave          NaT
25                                  127 Hours   2010-05-11
26                                         13          NaT
28                             13 Going on 30          NaT
29  13 Hours: The Secret Soldiers of Benghazi          NaT
30                                 13 Minutes          NaT
31                                    13 Sins          NaT

## Stage 1: Meta ↔ ExpertReviews Relationship

The Meta and ExpertReviews datasets share a common URL identifier.
This stage validates coverage and confirms the expected one-to-many
relationship between movies and expert reviews.

### 1.1 URL-based Relationship Inspection (NO MERGE)

In [57]:
meta_urls = set(meta_df['url'])
expert_urls = set(expert_df['url'])

# Intersection
common_urls = meta_urls.intersection(expert_urls)

print("Meta movies:", len(meta_urls))
print("Expert review movies:", len(expert_urls))
print("Common URLs:", len(common_urls))

print(
    "Percentage of Meta movies with ExpertReviews:",
    f"{len(common_urls) / len(meta_urls) * 100:.2f}%"
)

# Cardinality: number of expert reviews per movie
expert_review_counts = expert_df['url'].value_counts()

print("\nExpert review count summary:")
print(expert_review_counts.describe())

Meta movies: 11364
Expert review movies: 11364
Common URLs: 11364
Percentage of Meta movies with ExpertReviews: 100.00%

Expert review count summary:
count    11364.000000
mean        21.028951
std         11.590415
min          1.000000
25%         11.000000
50%         18.000000
75%         30.000000
max         67.000000
Name: count, dtype: float64

## Stage 2: Meta ↔ UserReviews Relationship

The Meta and UserReviews datasets also share a common URL identifier.
However, user reviews are optional, meaning not all movies receive
user-generated feedback. This stage validates coverage and review volume.

### 2.1 URL-based Relationship Inspection (NO MERGE)

In [58]:
meta_urls = set(meta_df['url'])
user_urls = set(user_df['url'])

# Intersection
common_urls = meta_urls.intersection(user_urls)

print("Meta movies:", len(meta_urls))
print("User review movies:", len(user_urls))
print("Common URLs:", len(common_urls))

print(
    "Percentage of Meta movies with UserReviews:",
    f"{len(common_urls) / len(meta_urls) * 100:.2f}%"
)

# Cardinality: number of user reviews per movie
user_review_counts = user_df['url'].value_counts()

print("\nUser review count summary:")
print(user_review_counts.describe())

Meta movies: 11364
User review movies: 8896
Common URLs: 8896
Percentage of Meta movies with UserReviews: 78.28%

User review count summary:
count    8896.000000
mean       35.550585
std       101.886194
min         1.000000
25%         2.000000
50%         8.000000
75%        29.000000
max      2763.000000
Name: count, dtype: float64

## Phase 3 Summary

- Meta serves as the anchor table, representing one row per movie.
- ExpertReviews and UserReviews exhibit clear one-to-many relationships
  with Meta using the URL identifier.
- The Sales dataset cannot be directly joined via URL but shows meaningful
  overlap when titles are used as a semantic linking key.
- No merges are performed in this phase; all relationships are evaluated
  conceptually and quantitatively to inform later integration decisions.